<?php


use Drupal\Core\Form\FormStateInterface;

function example_form_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {


// Alter all forms on the site.
// Example: Add a custom CSS class to all submit buttons.

if (isset($form['actions']['submit'])) {

$form['actions']['submit']['#attributes']['class'][] = 'custom-submit-class';
   }
}

 function example_form_form_example_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $form['additional_field'] = [
    '#type' => 'tel',
    '#title' => t('Phone number'),
  ];
  $form['#submit'][] = 'example_form_form_submit';

    }
    /**
     * Custom submit handler for Example form.
     */
function example_form_form_submit ($form, FormStateInterface $form_state) {

// Get the submitted phone number.

  $phone_number = $form_state->getValue('phone_number');

  \Drupal::messenger()->addMessage (t('Phone number updated successfully: @phone', ['@phone' => $phone_number]));

}

